<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll(): array
    {
        return $this->findBy(array(), array('creation' => 'DESC'));
    }
}
